const users = [
    { srNo: 1, userType: 'Admin', distributorId: 'D12345', userInfo: 'John Doe', loginStatus: true, userMobile: '9876543210', shopName: 'Shop A', aadharStatus: true, panStatus: true, emailStatus: true, walletBalance: 1500.75, permissions: { finance: true, travel: false, other: true }, status: 'Active' },
    { srNo: 2, userType: 'Distributor', distributorId: 'D12346', userInfo: 'Jane Smith', loginStatus: false, userMobile: '9876543211', shopName: 'Shop B', aadharStatus: true, panStatus: true, emailStatus: false, walletBalance: 1250.00, permissions: { finance: false, travel: true, other: false }, status: 'Blocked' },
    { srNo: 3, userType: 'Retailer', distributorId: 'D12347', userInfo: 'Alice Brown', loginStatus: true, userMobile: '9876543212', shopName: 'Shop C', aadharStatus: true, panStatus: false, emailStatus: true, walletBalance: 800.25, permissions: { finance: true, travel: true, other: true }, status: 'Active' },
    { srNo: 4, userType: 'Admin', distributorId: 'D12348', userInfo: 'Bob Green', loginStatus: true, userMobile: '9876543213', shopName: 'Shop D', aadharStatus: false, panStatus: true, emailStatus: true, walletBalance: 2200.50, permissions: { finance: true, travel: false, other: false }, status: 'Blocked' },
    { srNo: 5, userType: 'Distributor', distributorId: 'D12349', userInfo: 'Charlie White', loginStatus: false, userMobile: '9876543214', shopName: 'Shop E', aadharStatus: true, panStatus: true, emailStatus: false, walletBalance: 1100.00, permissions: { finance: false, travel: false, other: true }, status: 'Active' },
    { srNo: 6, userType: 'Retailer', distributorId: 'D12350', userInfo: 'David Black', loginStatus: true, userMobile: '9876543215', shopName: 'Shop F', aadharStatus: true, panStatus: true, emailStatus: true, walletBalance: 950.30, permissions: { finance: true, travel: true, other: false }, status: 'Blocked' },
    { srNo: 7, userType: 'Admin', distributorId: 'D12351', userInfo: 'Eva Blue', loginStatus: true, userMobile: '9876543216', shopName: 'Shop G', aadharStatus: false, panStatus: true, emailStatus: true, walletBalance: 1450.90, permissions: { finance: true, travel: true, other: false }, status: 'Active' },
    { srNo: 8, userType: 'Distributor', distributorId: 'D12352', userInfo: 'Frank Yellow', loginStatus: false, userMobile: '9876543217', shopName: 'Shop H', aadharStatus: true, panStatus: false, emailStatus: true, walletBalance: 2000.20, permissions: { finance: false, travel: true, other: true }, status: 'Blocked' },
    { srNo: 9, userType: 'Retailer', distributorId: 'D12353', userInfo: 'Grace Purple', loginStatus: true, userMobile: '9876543218', shopName: 'Shop I', aadharStatus: true, panStatus: true, emailStatus: true, walletBalance: 1200.50, permissions: { finance: true, travel: false, other: true }, status: 'Active' },
    { srNo: 10, userType: 'Admin', distributorId: 'D12354', userInfo: 'Hannah Orange', loginStatus: true, userMobile: '9876543219', shopName: 'Shop J', aadharStatus: true, panStatus: true, emailStatus: false, walletBalance: 2500.00, permissions: { finance: true, travel: true, other: true }, status: 'Blocked' },
    { srNo: 11, userType: 'Distributor', distributorId: 'D12355', userInfo: 'Ivy Gray', loginStatus: false, userMobile: '9876543220', shopName: 'Shop K', aadharStatus: true, panStatus: true, emailStatus: true, walletBalance: 900.60, permissions: { finance: false, travel: true, other: true }, status: 'Active' },
    { srNo: 12, userType: 'Retailer', distributorId: 'D12356', userInfo: 'Jack Red', loginStatus: true, userMobile: '9876543221', shopName: 'Shop L', aadharStatus: false, panStatus: true, emailStatus: true, walletBalance: 850.75, permissions: { finance: true, travel: false, other: false }, status: 'Blocked' },
    { srNo: 13, userType: 'Admin', distributorId: 'D12357', userInfo: 'Kathy Pink', loginStatus: true, userMobile: '9876543222', shopName: 'Shop M', aadharStatus: true, panStatus: false, emailStatus: true, walletBalance: 3000.00, permissions: { finance: true, travel: true, other: false }, status: 'Active' },
    { srNo: 14, userType: 'Distributor', distributorId: 'D12358', userInfo: 'Liam Brown', loginStatus: false, userMobile: '9876543223', shopName: 'Shop N', aadharStatus: true, panStatus: true, emailStatus: true, walletBalance: 1400.00, permissions: { finance: false, travel: true, other: true }, status: 'Blocked' },
    { srNo: 15, userType: 'Retailer', distributorId: 'D12359', userInfo: 'Mona Black', loginStatus: true, userMobile: '9876543224', shopName: 'Shop O', aadharStatus: true, panStatus: false, emailStatus: true, walletBalance: 700.90, permissions: { finance: true, travel: false, other: true }, status: 'Active' },
    { srNo: 16, userType: 'Admin', distributorId: 'D12360', userInfo: 'Nina White', loginStatus: true, userMobile: '9876543225', shopName: 'Shop P', aadharStatus: true, panStatus: true, emailStatus: true, walletBalance: 1750.50, permissions: { finance: true, travel: true, other: true }, status: 'Blocked' },
    { srNo: 17, userType: 'Distributor', distributorId: 'D12361', userInfo: 'Oscar Green', loginStatus: false, userMobile: '9876543226', shopName: 'Shop Q', aadharStatus: false, panStatus: true, emailStatus: false, walletBalance: 950.20, permissions: { finance: false, travel: false, other: true }, status: 'Active' },
    { srNo: 18, userType: 'Retailer', distributorId: 'D12362', userInfo: 'Paul Yellow', loginStatus: true, userMobile: '9876543227', shopName: 'Shop R', aadharStatus: true, panStatus: true, emailStatus: true, walletBalance: 650.60, permissions: { finance: true, travel: true, other: true }, status: 'Blocked' },
    { srNo: 19, userType: 'Admin', distributorId: 'D12363', userInfo: 'Quincy Blue', loginStatus: true, userMobile: '9876543228', shopName: 'Shop S', aadharStatus: false, panStatus: true, emailStatus: false, walletBalance: 4000.00, permissions: { finance: true, travel: false, other: false }, status: 'Active' },
    { srNo: 20, userType: 'Distributor', distributorId: 'D12364', userInfo: 'Rachel Orange', loginStatus: false, userMobile: '9876543229', shopName: 'Shop T', aadharStatus: true, panStatus: true, emailStatus: true, walletBalance: 1300.00, permissions: { finance: false, travel: true, other: true }, status: 'Blocked' },
  ];
  
  export default users;
  