const users = [
  {
    srNo: 1,
    userType: 'Retailer',
    distributorId: 'D12341',
    userInfo: 'User 1',
    loginStatus: false,
    userMobile: '987654321000',
    shopName: 'Shop A',
    aadharStatus: true,
    panStatus: false,
    emailStatus: false,
    walletBalance: '2354.29',
    permissions: { finance: false, travel: false, other: false },
    status: 'Active'
  },
  {
    srNo: 2,
    userType: 'Admin',
    distributorId: 'D12342',
    userInfo: 'User 2',
    loginStatus: false,
    userMobile: '987654321001',
    shopName: 'Shop B',
    aadharStatus: false,
    panStatus: false,
    emailStatus: true,
    walletBalance: '1383.00',
    permissions: { finance: true, travel: true, other: true },
    status: 'Active'
  },
  {
    srNo: 3,
    userType: 'Admin',
    distributorId: 'D12343',
    userInfo: 'User 3',
    loginStatus: false,
    userMobile: '987654321002',
    shopName: 'Shop C',
    aadharStatus: false,
    panStatus: false,
    emailStatus: true,
    walletBalance: '2531.34',
    permissions: { finance: false, travel: false, other: true },
    status: 'Active'
  },
  {
    srNo: 4,
    userType: 'Retailer',
    distributorId: 'D12344',
    userInfo: 'User 4',
    loginStatus: true,
    userMobile: '987654321003',
    shopName: 'Shop D',
    aadharStatus: false,
    panStatus: true,
    emailStatus: true,
    walletBalance: '8769.00',
    permissions: { finance: false, travel: false, other: true },
    status: 'Active'
  },
  {
    srNo: 5,
    userType: 'Admin',
    distributorId: 'D12345',
    userInfo: 'User 5',
    loginStatus: false,
    userMobile: '987654321004',
    shopName: 'Shop E',
    aadharStatus: false,
    panStatus: false,
    emailStatus: false,
    walletBalance: '4596.06',
    permissions: { finance: true, travel: false, other: true },
    status: 'Active'
  },
  {
    srNo: 6,
    userType: 'Distributor',
    distributorId: 'D12346',
    userInfo: 'User 6',
    loginStatus: false,
    userMobile: '987654321005',
    shopName: 'Shop F',
    aadharStatus: true,
    panStatus: true,
    emailStatus: true,
    walletBalance: '5388.27',
    permissions: { finance: true, travel: false, other: false },
    status: 'Blocked'
  },
  {
    srNo: 7,
    userType: 'Retailer',
    distributorId: 'D12347',
    userInfo: 'User 7',
    loginStatus: false,
    userMobile: '987654321006',
    shopName: 'Shop G',
    aadharStatus: true,
    panStatus: true,
    emailStatus: true,
    walletBalance: '9469.58',
    permissions: { finance: true, travel: true, other: false },
    status: 'Active'
  },
  {
    srNo: 8,
    userType: 'Distributor',
    distributorId: 'D12348',
    userInfo: 'User 8',
    loginStatus: false,
    userMobile: '987654321007',
    shopName: 'Shop H',
    aadharStatus: false,
    panStatus: true,
    emailStatus: true,
    walletBalance: '2321.27',
    permissions: { finance: true, travel: true, other: true },
    status: 'Blocked'
  },
  {
    srNo: 9,
    userType: 'Retailer',
    distributorId: 'D12349',
    userInfo: 'User 9',
    loginStatus: true,
    userMobile: '987654321008',
    shopName: 'Shop I',
    aadharStatus: false,
    panStatus: false,
    emailStatus: false,
    walletBalance: '5644.93',
    permissions: { finance: false, travel: true, other: false },
    status: 'Blocked'
  },
  {
    srNo: 10,
    userType: 'Retailer',
    distributorId: 'D123410',
    userInfo: 'User 10',
    loginStatus: true,
    userMobile: '987654321009',
    shopName: 'Shop J',
    aadharStatus: false,
    panStatus: false,
    emailStatus: true,
    walletBalance: '2668.93',
    permissions: { finance: false, travel: true, other: true },
    status: 'Active'
  },
  {
    srNo: 11,
    userType: 'Distributor',
    distributorId: 'D123411',
    userInfo: 'User 11',
    loginStatus: false,
    userMobile: '987654321010',
    shopName: 'Shop K',
    aadharStatus: true,
    panStatus: true,
    emailStatus: true,
    walletBalance: '6779.06',
    permissions: { finance: false, travel: false, other: false },
    status: 'Active'
  },
  {
    srNo: 12,
    userType: 'Admin',
    distributorId: 'D123412',
    userInfo: 'User 12',
    loginStatus: true,
    userMobile: '987654321011',
    shopName: 'Shop L',
    aadharStatus: false,
    panStatus: false,
    emailStatus: false,
    walletBalance: '3420.55',
    permissions: { finance: false, travel: false, other: false },
    status: 'Blocked'
  },
  {
    srNo: 13,
    userType: 'Admin',
    distributorId: 'D123413',
    userInfo: 'User 13',
    loginStatus: false,
    userMobile: '987654321012',
    shopName: 'Shop M',
    aadharStatus: true,
    panStatus: false,
    emailStatus: false,
    walletBalance: '5655.55',
    permissions: { finance: true, travel: true, other: true },
    status: 'Blocked'
  },
  {
    srNo: 14,
    userType: 'Retailer',
    distributorId: 'D123414',
    userInfo: 'User 14',
    loginStatus: false,
    userMobile: '987654321013',
    shopName: 'Shop N',
    aadharStatus: true,
    panStatus: false,
    emailStatus: false,
    walletBalance: '4481.29',
    permissions: { finance: false, travel: true, other: false },
    status: 'Active'
  },
  {
    srNo: 15,
    userType: 'Admin',
    distributorId: 'D123415',
    userInfo: 'User 15',
    loginStatus: false,
    userMobile: '987654321014',
    shopName: 'Shop O',
    aadharStatus: false,
    panStatus: false,
    emailStatus: true,
    walletBalance: '300.45',
    permissions: { finance: true, travel: true, other: true },
    status: 'Active'
  },
  {
    srNo: 16,
    userType: 'Distributor',
    distributorId: 'D123416',
    userInfo: 'User 16',
    loginStatus: true,
    userMobile: '987654321015',
    shopName: 'Shop P',
    aadharStatus: false,
    panStatus: false,
    emailStatus: false,
    walletBalance: '2815.02',
    permissions: { finance: true, travel: true, other: true },
    status: 'Blocked'
  },
  {
    srNo: 17,
    userType: 'Retailer',
    distributorId: 'D123417',
    userInfo: 'User 17',
    loginStatus: true,
    userMobile: '987654321016',
    shopName: 'Shop Q',
    aadharStatus: true,
    panStatus: false,
    emailStatus: false,
    walletBalance: '1209.86',
    permissions: { finance: false, travel: true, other: false },
    status: 'Active'
  },
  {
    srNo: 18,
    userType: 'Distributor',
    distributorId: 'D123418',
    userInfo: 'User 18',
    loginStatus: true,
    userMobile: '987654321017',
    shopName: 'Shop R',
    aadharStatus: false,
    panStatus: false,
    emailStatus: true,
    walletBalance: '8979.64',
    permissions: { finance: false, travel: false, other: false },
    status: 'Active'
  },
  {
    srNo: 19,
    userType: 'Distributor',
    distributorId: 'D123419',
    userInfo: 'User 19',
    loginStatus: true,
    userMobile: '987654321018',
    shopName: 'Shop S',
    aadharStatus: false,
    panStatus: false,
    emailStatus: false,
    walletBalance: '3981.83',
    permissions: { finance: true, travel: true, other: true },
    status: 'Blocked'
  },
  {
    srNo: 20,
    userType: 'Admin',
    distributorId: 'D123420',
    userInfo: 'User 20',
    loginStatus: true,
    userMobile: '987654321019',
    shopName: 'Shop T',
    aadharStatus: false,
    panStatus: false,
    emailStatus: false,
    walletBalance: '6105.56',
    permissions: { finance: true, travel: true, other: false },
    status: 'Active'
  },
  {
    srNo: 21,
    userType: 'Distributor',
    distributorId: 'D123421',
    userInfo: 'User 21',
    loginStatus: true,
    userMobile: '987654321020',
    shopName: 'Shop U',
    aadharStatus: false,
    panStatus: false,
    emailStatus: true,
    walletBalance: '4853.32',
    permissions: { finance: true, travel: false, other: true },
    status: 'Blocked'
  },
  {
    srNo: 22,
    userType: 'Admin',
    distributorId: 'D123422',
    userInfo: 'User 22',
    loginStatus: true,
    userMobile: '987654321021',
    shopName: 'Shop V',
    aadharStatus: true,
    panStatus: false,
    emailStatus: false,
    walletBalance: '9013.48',
    permissions: { finance: true, travel: false, other: false },
    status: 'Blocked'
  },
  {
    srNo: 23,
    userType: 'Admin',
    distributorId: 'D123423',
    userInfo: 'User 23',
    loginStatus: true,
    userMobile: '987654321022',
    shopName: 'Shop W',
    aadharStatus: true,
    panStatus: false,
    emailStatus: false,
    walletBalance: '5741.84',
    permissions: { finance: false, travel: true, other: false },
    status: 'Active'
  },
  {
    srNo: 24,
    userType: 'Admin',
    distributorId: 'D123424',
    userInfo: 'User 24',
    loginStatus: false,
    userMobile: '987654321023',
    shopName: 'Shop X',
    aadharStatus: true,
    panStatus: false,
    emailStatus: true,
    walletBalance: '6751.53',
    permissions: { finance: true, travel: true, other: true },
    status: 'Active'
  },
  {
    srNo: 25,
    userType: 'Admin',
    distributorId: 'D123425',
    userInfo: 'User 25',
    loginStatus: false,
    userMobile: '987654321024',
    shopName: 'Shop Y',
    aadharStatus: true,
    panStatus: true,
    emailStatus: false,
    walletBalance: '3374.20',
    permissions: { finance: false, travel: true, other: true },
    status: 'Active'
  },
  {
    srNo: 26,
    userType: 'Distributor',
    distributorId: 'D123426',
    userInfo: 'User 26',
    loginStatus: false,
    userMobile: '987654321025',
    shopName: 'Shop Z',
    aadharStatus: false,
    panStatus: true,
    emailStatus: false,
    walletBalance: '9929.70',
    permissions: { finance: true, travel: false, other: false },
    status: 'Blocked'
  },
  {
    srNo: 27,
    userType: 'Admin',
    distributorId: 'D123427',
    userInfo: 'User 27',
    loginStatus: false,
    userMobile: '987654321026',
    shopName: 'Shop A',
    aadharStatus: true,
    panStatus: false,
    emailStatus: true,
    walletBalance: '5031.92',
    permissions: { finance: true, travel: false, other: true },
    status: 'Active'
  },
  {
    srNo: 28,
    userType: 'Distributor',
    distributorId: 'D123428',
    userInfo: 'User 28',
    loginStatus: false,
    userMobile: '987654321027',
    shopName: 'Shop B',
    aadharStatus: false,
    panStatus: false,
    emailStatus: false,
    walletBalance: '3262.17',
    permissions: { finance: true, travel: false, other: true },
    status: 'Active'
  },
  {
    srNo: 29,
    userType: 'Distributor',
    distributorId: 'D123429',
    userInfo: 'User 29',
    loginStatus: false,
    userMobile: '987654321028',
    shopName: 'Shop C',
    aadharStatus: false,
    panStatus: true,
    emailStatus: true,
    walletBalance: '7012.12',
    permissions: { finance: false, travel: false, other: true },
    status: 'Blocked'
  },
  {
    srNo: 30,
    userType: 'Distributor',
    distributorId: 'D123430',
    userInfo: 'User 30',
    loginStatus: true,
    userMobile: '987654321029',
    shopName: 'Shop D',
    aadharStatus: true,
    panStatus: false,
    emailStatus: false,
    walletBalance: '6195.90',
    permissions: { finance: false, travel: false, other: false },
    status: 'Active'
  },
  {
    srNo: 31,
    userType: 'Admin',
    distributorId: 'D123431',
    userInfo: 'User 31',
    loginStatus: false,
    userMobile: '987654321030',
    shopName: 'Shop E',
    aadharStatus: false,
    panStatus: true,
    emailStatus: false,
    walletBalance: '2337.44',
    permissions: { finance: false, travel: true, other: false },
    status: 'Active'
  },
  {
    srNo: 32,
    userType: 'Admin',
    distributorId: 'D123432',
    userInfo: 'User 32',
    loginStatus: true,
    userMobile: '987654321031',
    shopName: 'Shop F',
    aadharStatus: false,
    panStatus: false,
    emailStatus: true,
    walletBalance: '3417.54',
    permissions: { finance: false, travel: true, other: false },
    status: 'Active'
  },
  {
    srNo: 33,
    userType: 'Admin',
    distributorId: 'D123433',
    userInfo: 'User 33',
    loginStatus: false,
    userMobile: '987654321032',
    shopName: 'Shop G',
    aadharStatus: true,
    panStatus: false,
    emailStatus: false,
    walletBalance: '8812.06',
    permissions: { finance: false, travel: true, other: true },
    status: 'Active'
  },
  {
    srNo: 34,
    userType: 'Admin',
    distributorId: 'D123434',
    userInfo: 'User 34',
    loginStatus: true,
    userMobile: '987654321033',
    shopName: 'Shop H',
    aadharStatus: false,
    panStatus: true,
    emailStatus: true,
    walletBalance: '9440.86',
    permissions: { finance: true, travel: true, other: true },
    status: 'Active'
  },
  {
    srNo: 35,
    userType: 'Distributor',
    distributorId: 'D123435',
    userInfo: 'User 35',
    loginStatus: false,
    userMobile: '987654321034',
    shopName: 'Shop I',
    aadharStatus: true,
    panStatus: false,
    emailStatus: true,
    walletBalance: '7424.85',
    permissions: { finance: false, travel: false, other: true },
    status: 'Active'
  },
  {
    srNo: 36,
    userType: 'Distributor',
    distributorId: 'D123436',
    userInfo: 'User 36',
    loginStatus: false,
    userMobile: '987654321035',
    shopName: 'Shop J',
    aadharStatus: false,
    panStatus: true,
    emailStatus: true,
    walletBalance: '5112.67',
    permissions: { finance: true, travel: false, other: false },
    status: 'Blocked'
  },
  {
    srNo: 37,
    userType: 'Retailer',
    distributorId: 'D123437',
    userInfo: 'User 37',
    loginStatus: true,
    userMobile: '987654321036',
    shopName: 'Shop K',
    aadharStatus: true,
    panStatus: true,
    emailStatus: false,
    walletBalance: '9853.54',
    permissions: { finance: true, travel: true, other: false },
    status: 'Blocked'
  },
  {
    srNo: 38,
    userType: 'Retailer',
    distributorId: 'D123438',
    userInfo: 'User 38',
    loginStatus: true,
    userMobile: '987654321037',
    shopName: 'Shop L',
    aadharStatus: false,
    panStatus: true,
    emailStatus: true,
    walletBalance: '9876.42',
    permissions: { finance: true, travel: true, other: false },
    status: 'Blocked'
  },
  {
    srNo: 39,
    userType: 'Distributor',
    distributorId: 'D123439',
    userInfo: 'User 39',
    loginStatus: false,
    userMobile: '987654321038',
    shopName: 'Shop M',
    aadharStatus: false,
    panStatus: false,
    emailStatus: false,
    walletBalance: '9635.99',
    permissions: { finance: false, travel: false, other: true },
    status: 'Active'
  },
  {
    srNo: 40,
    userType: 'Admin',
    distributorId: 'D123440',
    userInfo: 'User 40',
    loginStatus: true,
    userMobile: '987654321039',
    shopName: 'Shop N',
    aadharStatus: true,
    panStatus: true,
    emailStatus: false,
    walletBalance: '6774.52',
    permissions: { finance: true, travel: false, other: false },
    status: 'Blocked'
  },
  {
    srNo: 41,
    userType: 'Distributor',
    distributorId: 'D123441',
    userInfo: 'User 41',
    loginStatus: false,
    userMobile: '987654321040',
    shopName: 'Shop O',
    aadharStatus: false,
    panStatus: false,
    emailStatus: false,
    walletBalance: '9584.61',
    permissions: { finance: false, travel: true, other: false },
    status: 'Blocked'
  },
  {
    srNo: 42,
    userType: 'Admin',
    distributorId: 'D123442',
    userInfo: 'User 42',
    loginStatus: true,
    userMobile: '987654321041',
    shopName: 'Shop P',
    aadharStatus: false,
    panStatus: false,
    emailStatus: true,
    walletBalance: '1378.91',
    permissions: { finance: true, travel: false, other: false },
    status: 'Blocked'
  },
  {
    srNo: 43,
    userType: 'Retailer',
    distributorId: 'D123443',
    userInfo: 'User 43',
    loginStatus: true,
    userMobile: '987654321042',
    shopName: 'Shop Q',
    aadharStatus: true,
    panStatus: true,
    emailStatus: false,
    walletBalance: '1780.06',
    permissions: { finance: false, travel: false, other: false },
    status: 'Blocked'
  },
  {
    srNo: 44,
    userType: 'Distributor',
    distributorId: 'D123444',
    userInfo: 'User 44',
    loginStatus: true,
    userMobile: '987654321043',
    shopName: 'Shop R',
    aadharStatus: true,
    panStatus: true,
    emailStatus: true,
    walletBalance: '6244.96',
    permissions: { finance: false, travel: true, other: true },
    status: 'Blocked'
  },
  {
    srNo: 45,
    userType: 'Distributor',
    distributorId: 'D123445',
    userInfo: 'User 45',
    loginStatus: false,
    userMobile: '987654321044',
    shopName: 'Shop S',
    aadharStatus: true,
    panStatus: false,
    emailStatus: true,
    walletBalance: '5599.74',
    permissions: { finance: false, travel: false, other: false },
    status: 'Active'
  },
  {
    srNo: 46,
    userType: 'Admin',
    distributorId: 'D123446',
    userInfo: 'User 46',
    loginStatus: false,
    userMobile: '987654321045',
    shopName: 'Shop T',
    aadharStatus: true,
    panStatus: false,
    emailStatus: true,
    walletBalance: '7631.92',
    permissions: { finance: false, travel: false, other: false },
    status: 'Blocked'
  },
  {
    srNo: 47,
    userType: 'Retailer',
    distributorId: 'D123447',
    userInfo: 'User 47',
    loginStatus: true,
    userMobile: '987654321046',
    shopName: 'Shop U',
    aadharStatus: false,
    panStatus: false,
    emailStatus: true,
    walletBalance: '9221.20',
    permissions: { finance: true, travel: false, other: true },
    status: 'Blocked'
  },
  {
    srNo: 48,
    userType: 'Retailer',
    distributorId: 'D123448',
    userInfo: 'User 48',
    loginStatus: false,
    userMobile: '987654321047',
    shopName: 'Shop V',
    aadharStatus: false,
    panStatus: false,
    emailStatus: false,
    walletBalance: '9157.54',
    permissions: { finance: true, travel: false, other: false },
    status: 'Active'
  },
  {
    srNo: 49,
    userType: 'Admin',
    distributorId: 'D123449',
    userInfo: 'User 49',
    loginStatus: true,
    userMobile: '987654321048',
    shopName: 'Shop W',
    aadharStatus: true,
    panStatus: true,
    emailStatus: true,
    walletBalance: '5327.85',
    permissions: { finance: false, travel: true, other: false },
    status: 'Blocked'
  },
  {
    srNo: 50,
    userType: 'Retailer',
    distributorId: 'D123450',
    userInfo: 'User 50',
    loginStatus: false,
    userMobile: '987654321049',
    shopName: 'Shop X',
    aadharStatus: true,
    panStatus: true,
    emailStatus: true,
    walletBalance: '3326.34',
    permissions: { finance: true, travel: true, other: false },
    status: 'Active'
  },
  {
    srNo: 51,
    userType: 'Admin',
    distributorId: 'D123451',
    userInfo: 'User 51',
    loginStatus: false,
    userMobile: '987654321050',
    shopName: 'Shop Y',
    aadharStatus: false,
    panStatus: false,
    emailStatus: false,
    walletBalance: '8249.52',
    permissions: { finance: false, travel: false, other: false },
    status: 'Blocked'
  },
  {
    srNo: 52,
    userType: 'Retailer',
    distributorId: 'D123452',
    userInfo: 'User 52',
    loginStatus: false,
    userMobile: '987654321051',
    shopName: 'Shop Z',
    aadharStatus: false,
    panStatus: true,
    emailStatus: false,
    walletBalance: '5901.04',
    permissions: { finance: true, travel: false, other: true },
    status: 'Blocked'
  },
  {
    srNo: 53,
    userType: 'Retailer',
    distributorId: 'D123453',
    userInfo: 'User 53',
    loginStatus: false,
    userMobile: '987654321052',
    shopName: 'Shop A',
    aadharStatus: true,
    panStatus: false,
    emailStatus: false,
    walletBalance: '7272.08',
    permissions: { finance: false, travel: true, other: false },
    status: 'Active'
  },
  {
    srNo: 54,
    userType: 'Admin',
    distributorId: 'D123454',
    userInfo: 'User 54',
    loginStatus: true,
    userMobile: '987654321053',
    shopName: 'Shop B',
    aadharStatus: false,
    panStatus: false,
    emailStatus: true,
    walletBalance: '7131.69',
    permissions: { finance: false, travel: false, other: false },
    status: 'Blocked'
  },
  {
    srNo: 55,
    userType: 'Distributor',
    distributorId: 'D123455',
    userInfo: 'User 55',
    loginStatus: true,
    userMobile: '987654321054',
    shopName: 'Shop C',
    aadharStatus: true,
    panStatus: false,
    emailStatus: false,
    walletBalance: '5277.05',
    permissions: { finance: true, travel: false, other: false },
    status: 'Active'
  },
  {
    srNo: 56,
    userType: 'Retailer',
    distributorId: 'D123456',
    userInfo: 'User 56',
    loginStatus: true,
    userMobile: '987654321055',
    shopName: 'Shop D',
    aadharStatus: false,
    panStatus: true,
    emailStatus: false,
    walletBalance: '3737.30',
    permissions: { finance: true, travel: true, other: false },
    status: 'Blocked'
  },
  {
    srNo: 57,
    userType: 'Retailer',
    distributorId: 'D123457',
    userInfo: 'User 57',
    loginStatus: true,
    userMobile: '987654321056',
    shopName: 'Shop E',
    aadharStatus: true,
    panStatus: true,
    emailStatus: true,
    walletBalance: '1318.86',
    permissions: { finance: false, travel: true, other: false },
    status: 'Active'
  },
  {
    srNo: 58,
    userType: 'Distributor',
    distributorId: 'D123458',
    userInfo: 'User 58',
    loginStatus: false,
    userMobile: '987654321057',
    shopName: 'Shop F',
    aadharStatus: false,
    panStatus: false,
    emailStatus: false,
    walletBalance: '5011.31',
    permissions: { finance: true, travel: false, other: true },
    status: 'Active'
  },
  {
    srNo: 59,
    userType: 'Distributor',
    distributorId: 'D123459',
    userInfo: 'User 59',
    loginStatus: true,
    userMobile: '987654321058',
    shopName: 'Shop G',
    aadharStatus: true,
    panStatus: false,
    emailStatus: false,
    walletBalance: '414.45',
    permissions: { finance: false, travel: true, other: false },
    status: 'Active'
  },
  {
    srNo: 60,
    userType: 'Admin',
    distributorId: 'D123460',
    userInfo: 'User 60',
    loginStatus: false,
    userMobile: '987654321059',
    shopName: 'Shop H',
    aadharStatus: true,
    panStatus: true,
    emailStatus: true,
    walletBalance: '1823.13',
    permissions: { finance: false, travel: false, other: false },
    status: 'Blocked'
  },
  {
    srNo: 61,
    userType: 'Distributor',
    distributorId: 'D123461',
    userInfo: 'User 61',
    loginStatus: false,
    userMobile: '987654321060',
    shopName: 'Shop I',
    aadharStatus: false,
    panStatus: false,
    emailStatus: false,
    walletBalance: '8322.60',
    permissions: { finance: true, travel: false, other: false },
    status: 'Active'
  },
  {
    srNo: 62,
    userType: 'Retailer',
    distributorId: 'D123462',
    userInfo: 'User 62',
    loginStatus: false,
    userMobile: '987654321061',
    shopName: 'Shop J',
    aadharStatus: true,
    panStatus: false,
    emailStatus: true,
    walletBalance: '1108.79',
    permissions: { finance: true, travel: false, other: false },
    status: 'Blocked'
  },
  {
    srNo: 63,
    userType: 'Distributor',
    distributorId: 'D123463',
    userInfo: 'User 63',
    loginStatus: false,
    userMobile: '987654321062',
    shopName: 'Shop K',
    aadharStatus: true,
    panStatus: true,
    emailStatus: true,
    walletBalance: '3039.01',
    permissions: { finance: false, travel: true, other: false },
    status: 'Blocked'
  },
  {
    srNo: 64,
    userType: 'Retailer',
    distributorId: 'D123464',
    userInfo: 'User 64',
    loginStatus: false,
    userMobile: '987654321063',
    shopName: 'Shop L',
    aadharStatus: false,
    panStatus: false,
    emailStatus: true,
    walletBalance: '7326.95',
    permissions: { finance: false, travel: false, other: false },
    status: 'Active'
  },
  {
    srNo: 65,
    userType: 'Retailer',
    distributorId: 'D123465',
    userInfo: 'User 65',
    loginStatus: true,
    userMobile: '987654321064',
    shopName: 'Shop M',
    aadharStatus: true,
    panStatus: true,
    emailStatus: true,
    walletBalance: '8752.38',
    permissions: { finance: false, travel: true, other: true },
    status: 'Active'
  },
  {
    srNo: 66,
    userType: 'Retailer',
    distributorId: 'D123466',
    userInfo: 'User 66',
    loginStatus: false,
    userMobile: '987654321065',
    shopName: 'Shop N',
    aadharStatus: true,
    panStatus: false,
    emailStatus: false,
    walletBalance: '7862.56',
    permissions: { finance: true, travel: false, other: true },
    status: 'Active'
  },
  {
    srNo: 67,
    userType: 'Distributor',
    distributorId: 'D123467',
    userInfo: 'User 67',
    loginStatus: false,
    userMobile: '987654321066',
    shopName: 'Shop O',
    aadharStatus: false,
    panStatus: true,
    emailStatus: false,
    walletBalance: '725.33',
    permissions: { finance: true, travel: false, other: false },
    status: 'Blocked'
  },
  {
    srNo: 68,
    userType: 'Admin',
    distributorId: 'D123468',
    userInfo: 'User 68',
    loginStatus: false,
    userMobile: '987654321067',
    shopName: 'Shop P',
    aadharStatus: true,
    panStatus: true,
    emailStatus: true,
    walletBalance: '4614.09',
    permissions: { finance: true, travel: true, other: true },
    status: 'Active'
  },
  {
    srNo: 69,
    userType: 'Retailer',
    distributorId: 'D123469',
    userInfo: 'User 69',
    loginStatus: false,
    userMobile: '987654321068',
    shopName: 'Shop Q',
    aadharStatus: true,
    panStatus: true,
    emailStatus: true,
    walletBalance: '2788.76',
    permissions: { finance: false, travel: true, other: true },
    status: 'Blocked'
  },
  {
    srNo: 70,
    userType: 'Distributor',
    distributorId: 'D123470',
    userInfo: 'User 70',
    loginStatus: true,
    userMobile: '987654321069',
    shopName: 'Shop R',
    aadharStatus: false,
    panStatus: false,
    emailStatus: false,
    walletBalance: '8824.59',
    permissions: { finance: false, travel: true, other: true },
    status: 'Blocked'
  },
  {
    srNo: 71,
    userType: 'Distributor',
    distributorId: 'D123471',
    userInfo: 'User 71',
    loginStatus: false,
    userMobile: '987654321070',
    shopName: 'Shop S',
    aadharStatus: true,
    panStatus: false,
    emailStatus: true,
    walletBalance: '6604.85',
    permissions: { finance: false, travel: true, other: false },
    status: 'Blocked'
  },
  {
    srNo: 72,
    userType: 'Retailer',
    distributorId: 'D123472',
    userInfo: 'User 72',
    loginStatus: true,
    userMobile: '987654321071',
    shopName: 'Shop T',
    aadharStatus: false,
    panStatus: true,
    emailStatus: true,
    walletBalance: '2112.74',
    permissions: { finance: true, travel: false, other: false },
    status: 'Active'
  },
  {
    srNo: 73,
    userType: 'Retailer',
    distributorId: 'D123473',
    userInfo: 'User 73',
    loginStatus: true,
    userMobile: '987654321072',
    shopName: 'Shop U',
    aadharStatus: false,
    panStatus: false,
    emailStatus: true,
    walletBalance: '7455.29',
    permissions: { finance: true, travel: true, other: false },
    status: 'Blocked'
  },
  {
    srNo: 74,
    userType: 'Admin',
    distributorId: 'D123474',
    userInfo: 'User 74',
    loginStatus: false,
    userMobile: '987654321073',
    shopName: 'Shop V',
    aadharStatus: false,
    panStatus: false,
    emailStatus: false,
    walletBalance: '8352.29',
    permissions: { finance: false, travel: false, other: false },
    status: 'Blocked'
  },
  {
    srNo: 75,
    userType: 'Admin',
    distributorId: 'D123475',
    userInfo: 'User 75',
    loginStatus: false,
    userMobile: '987654321074',
    shopName: 'Shop W',
    aadharStatus: true,
    panStatus: false,
    emailStatus: false,
    walletBalance: '79.41',
    permissions: { finance: true, travel: false, other: true },
    status: 'Active'
  },
  {
    srNo: 76,
    userType: 'Admin',
    distributorId: 'D123476',
    userInfo: 'User 76',
    loginStatus: false,
    userMobile: '987654321075',
    shopName: 'Shop X',
    aadharStatus: true,
    panStatus: true,
    emailStatus: false,
    walletBalance: '6651.91',
    permissions: { finance: false, travel: false, other: true },
    status: 'Blocked'
  },
  {
    srNo: 77,
    userType: 'Admin',
    distributorId: 'D123477',
    userInfo: 'User 77',
    loginStatus: false,
    userMobile: '987654321076',
    shopName: 'Shop Y',
    aadharStatus: false,
    panStatus: true,
    emailStatus: true,
    walletBalance: '2741.02',
    permissions: { finance: true, travel: false, other: true },
    status: 'Active'
  },
  {
    srNo: 78,
    userType: 'Admin',
    distributorId: 'D123478',
    userInfo: 'User 78',
    loginStatus: false,
    userMobile: '987654321077',
    shopName: 'Shop Z',
    aadharStatus: false,
    panStatus: false,
    emailStatus: false,
    walletBalance: '8840.02',
    permissions: { finance: false, travel: false, other: true },
    status: 'Blocked'
  },
  {
    srNo: 79,
    userType: 'Admin',
    distributorId: 'D123479',
    userInfo: 'User 79',
    loginStatus: true,
    userMobile: '987654321078',
    shopName: 'Shop A',
    aadharStatus: false,
    panStatus: false,
    emailStatus: true,
    walletBalance: '8685.57',
    permissions: { finance: false, travel: true, other: true },
    status: 'Active'
  },
  {
    srNo: 80,
    userType: 'Retailer',
    distributorId: 'D123480',
    userInfo: 'User 80',
    loginStatus: true,
    userMobile: '987654321079',
    shopName: 'Shop B',
    aadharStatus: false,
    panStatus: true,
    emailStatus: true,
    walletBalance: '5820.78',
    permissions: { finance: true, travel: false, other: false },
    status: 'Blocked'
  },
  {
    srNo: 81,
    userType: 'Retailer',
    distributorId: 'D123481',
    userInfo: 'User 81',
    loginStatus: false,
    userMobile: '987654321080',
    shopName: 'Shop C',
    aadharStatus: true,
    panStatus: true,
    emailStatus: true,
    walletBalance: '9012.89',
    permissions: { finance: true, travel: true, other: true },
    status: 'Blocked'
  },
  {
    srNo: 82,
    userType: 'Distributor',
    distributorId: 'D123482',
    userInfo: 'User 82',
    loginStatus: false,
    userMobile: '987654321081',
    shopName: 'Shop D',
    aadharStatus: true,
    panStatus: true,
    emailStatus: false,
    walletBalance: '8362.83',
    permissions: { finance: false, travel: true, other: false },
    status: 'Active'
  },
  {
    srNo: 83,
    userType: 'Admin',
    distributorId: 'D123483',
    userInfo: 'User 83',
    loginStatus: false,
    userMobile: '987654321082',
    shopName: 'Shop E',
    aadharStatus: true,
    panStatus: false,
    emailStatus: false,
    walletBalance: '2102.78',
    permissions: { finance: true, travel: true, other: true },
    status: 'Blocked'
  },
  {
    srNo: 84,
    userType: 'Retailer',
    distributorId: 'D123484',
    userInfo: 'User 84',
    loginStatus: true,
    userMobile: '987654321083',
    shopName: 'Shop F',
    aadharStatus: false,
    panStatus: false,
    emailStatus: false,
    walletBalance: '4318.08',
    permissions: { finance: false, travel: true, other: true },
    status: 'Active'
  },
  {
    srNo: 85,
    userType: 'Admin',
    distributorId: 'D123485',
    userInfo: 'User 85',
    loginStatus: true,
    userMobile: '987654321084',
    shopName: 'Shop G',
    aadharStatus: false,
    panStatus: true,
    emailStatus: true,
    walletBalance: '5571.99',
    permissions: { finance: true, travel: false, other: true },
    status: 'Active'
  },
  {
    srNo: 86,
    userType: 'Admin',
    distributorId: 'D123486',
    userInfo: 'User 86',
    loginStatus: false,
    userMobile: '987654321085',
    shopName: 'Shop H',
    aadharStatus: false,
    panStatus: false,
    emailStatus: true,
    walletBalance: '9759.48',
    permissions: { finance: false, travel: false, other: false },
    status: 'Blocked'
  },
  {
    srNo: 87,
    userType: 'Admin',
    distributorId: 'D123487',
    userInfo: 'User 87',
    loginStatus: false,
    userMobile: '987654321086',
    shopName: 'Shop I',
    aadharStatus: true,
    panStatus: false,
    emailStatus: true,
    walletBalance: '3087.02',
    permissions: { finance: false, travel: true, other: true },
    status: 'Active'
  },
  {
    srNo: 88,
    userType: 'Retailer',
    distributorId: 'D123488',
    userInfo: 'User 88',
    loginStatus: false,
    userMobile: '987654321087',
    shopName: 'Shop J',
    aadharStatus: false,
    panStatus: false,
    emailStatus: true,
    walletBalance: '5949.39',
    permissions: { finance: false, travel: true, other: false },
    status: 'Active'
  },
  {
    srNo: 89,
    userType: 'Admin',
    distributorId: 'D123489',
    userInfo: 'User 89',
    loginStatus: false,
    userMobile: '987654321088',
    shopName: 'Shop K',
    aadharStatus: false,
    panStatus: true,
    emailStatus: false,
    walletBalance: '7445.81',
    permissions: { finance: false, travel: false, other: false },
    status: 'Active'
  },
  {
    srNo: 90,
    userType: 'Retailer',
    distributorId: 'D123490',
    userInfo: 'User 90',
    loginStatus: false,
    userMobile: '987654321089',
    shopName: 'Shop L',
    aadharStatus: true,
    panStatus: false,
    emailStatus: true,
    walletBalance: '9037.88',
    permissions: { finance: false, travel: true, other: false },
    status: 'Blocked'
  },
  {
    srNo: 91,
    userType: 'Admin',
    distributorId: 'D123491',
    userInfo: 'User 91',
    loginStatus: true,
    userMobile: '987654321090',
    shopName: 'Shop M',
    aadharStatus: true,
    panStatus: true,
    emailStatus: true,
    walletBalance: '5695.56',
    permissions: { finance: true, travel: true, other: true },
    status: 'Blocked'
  },
  {
    srNo: 92,
    userType: 'Distributor',
    distributorId: 'D123492',
    userInfo: 'User 92',
    loginStatus: false,
    userMobile: '987654321091',
    shopName: 'Shop N',
    aadharStatus: false,
    panStatus: false,
    emailStatus: false,
    walletBalance: '8961.04',
    permissions: { finance: true, travel: true, other: true },
    status: 'Blocked'
  },
  {
    srNo: 93,
    userType: 'Distributor',
    distributorId: 'D123493',
    userInfo: 'User 93',
    loginStatus: true,
    userMobile: '987654321092',
    shopName: 'Shop O',
    aadharStatus: true,
    panStatus: true,
    emailStatus: false,
    walletBalance: '1973.83',
    permissions: { finance: false, travel: true, other: false },
    status: 'Blocked'
  },
  {
    srNo: 94,
    userType: 'Distributor',
    distributorId: 'D123494',
    userInfo: 'User 94',
    loginStatus: true,
    userMobile: '987654321093',
    shopName: 'Shop P',
    aadharStatus: false,
    panStatus: true,
    emailStatus: false,
    walletBalance: '7831.66',
    permissions: { finance: true, travel: false, other: true },
    status: 'Blocked'
  },
  {
    srNo: 95,
    userType: 'Admin',
    distributorId: 'D123495',
    userInfo: 'User 95',
    loginStatus: true,
    userMobile: '987654321094',
    shopName: 'Shop Q',
    aadharStatus: false,
    panStatus: true,
    emailStatus: false,
    walletBalance: '4283.89',
    permissions: { finance: false, travel: true, other: false },
    status: 'Blocked'
  },
  {
    srNo: 96,
    userType: 'Retailer',
    distributorId: 'D123496',
    userInfo: 'User 96',
    loginStatus: true,
    userMobile: '987654321095',
    shopName: 'Shop R',
    aadharStatus: true,
    panStatus: true,
    emailStatus: false,
    walletBalance: '5715.19',
    permissions: { finance: true, travel: true, other: false },
    status: 'Active'
  },
  {
    srNo: 97,
    userType: 'Retailer',
    distributorId: 'D123497',
    userInfo: 'User 97',
    loginStatus: true,
    userMobile: '987654321096',
    shopName: 'Shop S',
    aadharStatus: true,
    panStatus: true,
    emailStatus: false,
    walletBalance: '6449.80',
    permissions: { finance: false, travel: true, other: false },
    status: 'Blocked'
  },
  {
    srNo: 98,
    userType: 'Retailer',
    distributorId: 'D123498',
    userInfo: 'User 98',
    loginStatus: true,
    userMobile: '987654321097',
    shopName: 'Shop T',
    aadharStatus: true,
    panStatus: false,
    emailStatus: false,
    walletBalance: '5967.33',
    permissions: { finance: true, travel: false, other: true },
    status: 'Blocked'
  },
  {
    srNo: 99,
    userType: 'Admin',
    distributorId: 'D123499',
    userInfo: 'User 99',
    loginStatus: true,
    userMobile: '987654321098',
    shopName: 'Shop U',
    aadharStatus: true,
    panStatus: false,
    emailStatus: true,
    walletBalance: '5286.46',
    permissions: { finance: false, travel: true, other: true },
    status: 'Active'
  },
  {
    srNo: 100,
    userType: 'Retailer',
    distributorId: 'D1234100',
    userInfo: 'User 100',
    loginStatus: false,
    userMobile: '987654321099',
    shopName: 'Shop V',
    aadharStatus: false,
    panStatus: true,
    emailStatus: true,
    walletBalance: '2507.67',
    permissions: { finance: true, travel: false, other: true },
    status: 'Blocked'
  },
];
  
  export default users;
  